import "MainPageViewModel.idl";

namespace raydbg
{
    [default_interface]
    runtimeclass MainPage : Windows.UI.Xaml.Controls.Page
    {
        MainPage();
        MainPageViewModel ViewModel{ get; };
    }
}
