namespace raydbg{
namespace ViewEntities {
    struct Point {
        Single x;
        Single y;
        Single z;
        Single w;
    };

    struct Vector{
        Single x;
        Single y;
        Single z;
        Single w;
    };

    struct Ray{
        Point o;
        Vector d;
    };

    struct LineSegment{
        Ray ray;
        Single t;
    };
}
}
