import "ViewEntities.idl";

namespace raydbg{
    runtimeclass MainPageViewModel {
        MainPageViewModel();
        Windows.Foundation.Collections.IObservableVector<raydbg.ViewEntities.LineSegment> RayList{ get; };
        event Windows.Foundation.EventHandler<Object> RayListUpdated;
    }
}