import "ViewEntities.idl";

namespace raydbg{
    static runtimeclass StringUtils{
        [default_overload]
        static String GetString(raydbg.ViewEntities.Point pot);
        static String GetString(raydbg.ViewEntities.Vector vec);
        static String GetString(raydbg.ViewEntities.Ray ray);
        static String GetString(Single f);
    }
}